//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangManGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HangManGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monopolio
        ///acorazado
        ///riesgo
        ///uno
        ///jenga
        ///clave.
        /// </summary>
        internal static string boardGameES {
            get {
                return ResourceManager.GetString("boardGameES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monopoly
        ///battleship
        ///sorry
        ///risk
        ///uno
        ///jenga
        ///clue.
        /// </summary>
        internal static string boardGames {
            get {
                return ResourceManager.GetString("boardGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to monopoly
        ///risque
        ///uno
        ///jenga
        ///indice.
        /// </summary>
        internal static string boardGamesFR {
            get {
                return ResourceManager.GetString("boardGamesFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loop
        ///object
        ///iteration
        ///programming
        ///thread
        ///database
        ///collection
        ///recursion
        ///lambda
        ///methods
        ///inheritance.
        /// </summary>
        internal static string computerScience {
            get {
                return ResourceManager.GetString("computerScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to circulo
        ///objeto
        ///iteracion
        ///programacion
        ///recopilacion
        ///recursion
        ///lambda
        ///metodos.
        /// </summary>
        internal static string computerScienceES {
            get {
                return ResourceManager.GetString("computerScienceES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to boucle
        ///objet
        ///iteration
        ///programmation
        ///lambda.
        /// </summary>
        internal static string computerScienceFR {
            get {
                return ResourceManager.GetString("computerScienceFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman_0 {
            get {
                object obj = ResourceManager.GetObject("hangman_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman_1 {
            get {
                object obj = ResourceManager.GetObject("hangman_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman_2 {
            get {
                object obj = ResourceManager.GetObject("hangman_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman_3 {
            get {
                object obj = ResourceManager.GetObject("hangman_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman_4 {
            get {
                object obj = ResourceManager.GetObject("hangman_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman_5 {
            get {
                object obj = ResourceManager.GetObject("hangman_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hangman_6 {
            get {
                object obj = ResourceManager.GetObject("hangman_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basketball
        ///football
        ///baseball
        ///volleyball
        ///hockey
        ///tennis
        ///golf
        ///boxe.
        /// </summary>
        internal static string sportFR {
            get {
                return ResourceManager.GetString("sportFR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to basketball
        ///football
        ///soccer
        ///baseball
        ///volleyball
        ///hockey
        ///tennis
        ///golf
        ///rugby
        ///boxing
        ///surfing.
        /// </summary>
        internal static string sports {
            get {
                return ResourceManager.GetString("sports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to baloncesto
        ///futbol
        ///beisbol
        ///voleibol.
        /// </summary>
        internal static string sportsES {
            get {
                return ResourceManager.GetString("sportsES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap title {
            get {
                object obj = ResourceManager.GetObject("title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
